trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'WebUI/WebUI.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'WebUI/WebUI.csproj'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true

