trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/UI

pr: none 

pool:
  vmImage: ubuntu-latest

stages:  
- stage: Development  
  jobs:  
  - job: BuildAndRelease  
    variables:
      globalHeaders.Blazor-Environment: Development
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/src/UI/WebUI'
        fileType: 'json'
        targetFiles: 'staticwebapp.config.json'
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/src/UI/WebUI'
        app_build_command: 'dotnet build'
        output_location: 'wwwroot'
        config_file_location: '/src/UI/WebUI'
        build_timeout_in_minutes: 5
        azure_static_web_apps_api_token: "$(stapp-farmerui-dev-token)"
        
- stage: Production  
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  jobs:  
  - job: BuildAndRelease  
    variables:
      globalHeaders.Blazor-Environment: Production
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/src/UI/WebUI'
        fileType: 'json'
        targetFiles: 'staticwebapp.config.json'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/src/UI/WebUI'
        app_build_command: 'dotnet build'
        output_location: 'wwwroot'
        config_file_location: '/src/UI/WebUI'
        build_timeout_in_minutes: 5
        azure_static_web_apps_api_token: "$(stapp-farmerui-prod-token)"