trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - WebUI

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Debug'

stages:

- stage: Analyze
  displayName: SonarCloud Analysis Stage
  jobs:
  - job: SonarCloudAnalyze
    displayName: Run SonarCloud Analysis
    steps:
    - task: SonarCloudPrepare@3
      displayName: Prepare
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'petar1808'
        scannerMode: 'cli'
        configMode: 'file'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: 'Farmer.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: 'Farmer.sln'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/**.csproj'
        arguments: '--configuration $(testConfiguration) --collect "Code Coverage"'
      continueOnError: false
    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud Analysis'
      inputs:
        jdkversion: 'JAVA_HOME_17_X64' 
    - task: SonarCloudPublish@3
      displayName: 'Publish'
      inputs:
        pollingTimeoutSec: '300'
      

- stage: Build
  displayName: Build and Publish Stage
  dependsOn: Analyze
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'],'refs/heads/main'), startsWith(variables['Build.SourceBranch'],'refs/heads/release/')))
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - script: dotnet restore WebApi
      displayName: 'dotnet restore'
    - script: dotnet build  WebApi --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish $(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'WebApi'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifacts'
