trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/UI
      - README.md

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  system.debug: 'true'

stages:

- stage: Analyze
  displayName: SonarCloud Analysis Stage
  jobs:
  - job: SonarCloudAnalyze
    displayName: Run SonarCloud Analysis
    steps:
    - task: SonarCloudPrepare@3
      displayName: Prepare
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'petar1808'
        scannerMode: 'cli'
        configMode: 'file'
        configFile: '$(System.DefaultWorkingDirectory)/src/API/sonar-project.properties'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/WebApi.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/WebApi.csproj'
        arguments: '--no-restore'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
        arguments: '--collect "Code Coverage"'
        testRunTitle: 'Api tests'
      continueOnError: false
    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud Analysis'
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: SonarCloudPublish@3
      displayName: 'Publish'
      inputs:
        pollingTimeoutSec: '300'
      
- stage: Build
  displayName: Build and Publish Stage
  dependsOn: Analyze
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'],'refs/heads/main'), startsWith(variables['Build.SourceBranch'],'refs/heads/release/')))
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/WebApi.csproj'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/WebApi.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish $(buildConfiguration)'
      inputs:
        command: publish
        publishWebProjects: false
        projects: 'WebApi'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifacts'
