trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/UI
      - README.md

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  system.debug: 'true'

stages:
- stage: Build
  displayName: Build and Publish Stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'farmer-api'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
    
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'farmer-api'
        command: 'push'
        tags: '$(Build.BuildId)'
